spring:
  data:
    mongodb:
      uri: mongodb+srv://tigeradmin:1qkpSPbesQXg5TVm@collabothon2023.9vwftyu.mongodb.net/tigerdb?retryWrites=true&w=majority
      database: tigerdb

# JWT
chonov:
  app:
    jwtSecret: chonoSecretKey
    jwtExpirationMs: 86400000

# Cors
web:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"

